;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        my/backward-word
        my/forward-word
        org-delete-char
        org-yank
        yaml-electric-dash-and-dot
        ))
